### ISSUE TITLE
persisting problem with file fc-spanish.def

### ISSUE THREAD

**Issue by simonkramer** [nlct/fmtcount#17]
Sorry to insist, but there is a persisting problem with file fc-spanish.def :

I get the same error message as in the (closed) issue "Problems with file fc-spanish.def" 
with the file /usr/local/texlive/2014/texmf-dist/tex/latex/fmtcount/fc-spanish.def .

So the problem has not really been solved or has been reintroduced.
Please, could this issue be fixed as soon as possible?

(The English, German, French and Italian files are unproblematic.)

Many thanks!

**Comment by vincentb1** [comment]
Hello,

No problem for your insisting :wink: !

Could you please check that the problem is still there with the latest `fmtcount` (not that of TeXLive). Let `/some/directory` be some temporary directory where you have placed the `LaTeX`  files to compile, then you can get the latest `fmtcount` as follows:
```bash
cd /some/directory
mkdir ./texmf
git clone https://github.com/nlct/fmtcount.git
make -C ./dist install TEXMF_INSTALL_DIR=./texmf
cp ./texmf/tex/latex/fmtcount/*.sty .
cp ./texmf/tex/latex/fmtcount/*.def .
```

**Comment by simonkramer** [comment]
Hello, Thank you for your quick reply :-)

Sorry, following your instructions with "cd /Users/simonkramer/Desktop" for "cd /some/directory", 
the make-command leads to the error message "make: *** ./dist: No such file or directory.  Stop."

If instead of executing your make-command, I execute the make-command 
"make -C ./fmtcount/dist install TEXMF_INSTALL_DIR=./texmf", 
then I get the following error message:

"/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../trunk dist
makedtx -author "Nicola Talbot and Vincent Belaïche" \
		-src "(.+)\.(sty|def)$=>\1.\2" \
		-doc fmtcount-manual.tex fmtcount
/bin/bash: makedtx: command not found
make[1]: *** [../dist/fmtcount.dtx] Error 127
make: *** [fmtcount.dtx] Error 2"

(I work in OSX Yosemite 10.10.2.)

**Comment by vincentb1** [comment]
Ok, sorry for that, you just need to install makedtx, this is a perl script that you can find on the CTAN, here: http://www.ctan.org/pkg/makedtx

Just copy the makedtx perl script to somewhere in your path (e.g. to `/usr/bin`), on my machine it is in `/local/bin`. You may also need to do the following:
* edit the first line of the script (for me I changed it to `#!/perl/bin/perl`) in order to have the path to the perl engine that you want to us
* make some chmod to make it executable (I did not need that because I am on MSWindows 7 + MSYS)

**Comment by simonkramer** [comment]
OK, thanks, that solved my (local) problem :-)
So /usr/local/texlive/2014/texmf-dist/tex/latex/fmtcount/fc-spanish.def definitely needs fixing!

**Comment by vincentb1** [comment]
Ok, thank you for pointing that to us, I will write to Karl Berry to inform him that TL is not uptodate w.r.t. to fmtcount.

Below I just recall the script to get fmtcount installation source, for completeness of this thread (in my first post I had just written it from the top of my head, hence the error that you noted):

```bash
cd /some/directory
mkdir ./texmf
git clone https://github.com/nlct/fmtcount.git
make -C ./fmtcount/dist install TEXMF_INSTALL_DIR=./texmf
cp ./texmf/tex/latex/fmtcount/*.sty .
cp ./texmf/tex/latex/fmtcount/*.def .
```

**Comment by vincentb1** [comment]
By the way, @simonkramer, please do me a favor: could you check whether your issue also exists with the latest delivery on CTAN: http://www.ctan.org/pkg/fmtcount

I would like to know whether we need to deliver again to CTAN before asking Karl to make any update.

**Comment by simonkramer** [comment]
My issue does NOT exist with the latest delivery on CTAN (dated 2014-07-18). I have just tested it. My issue arises through using your software as part of the MacTeX-2014 distribution (dated 2014-05-25, and thus prior to yours; https://tug.org/mactex/). So if I'm not mistaken, then the issue is due to your latest delivery not being part of the latest MacTeX-2014 delivery.

**Comment by vincentb1** [comment]
Dear Nicola @nlct,

Don't you think that I should make a delivery to CTAN of the GIT-latest fmtcount &mdash; ie containing correction for issue #16 &mdash; before asking Karl Berry to take the CTAN-latest into the next TL.

&nbsp;&nbsp;&nbsp;Vincent.

**Comment by nlct** [comment]
@vincentb1 Yes, I think it's a good idea to upload the latest version to CTAN. (TL usually don't need to be informed of updates as they should automatically detect them.) However, the LaTeX Team are doing some major uploads to CTAN at the moment, so it might be better to defer the fmtcount upload until after the Easter weekend unless you feel it's really urgent to do it immediately.

**Comment by simonkramer** [comment]
Addendum: 

With the system state corresponding to my previous message, I get the following error message: 

[35] (/usr/local/texlive/2014/texmf-dist/tex/latex/fmtcount/fc-english.def)
! Undefined control sequence.
\@ordinalMenglish ...lax \@ordinalctr =#1\@modulo 
                                                  {\@ordinalctr }{100}\ifnum...

with both (!) the "portuguese"- as well as the "english"-polyglossia option.

P.S. By the way, which languages are actually available as options?

**Comment by nlct** [comment]
That should be `\@FCmodulo`. It looks like you have an old version of `fc-english.def`. (It was renamed to avoid conflict with another package that also defined a command called `\@modulo`.)

Language options are: `english`, `french`, `german`, `portuguese` and `spanish`. There's also `italian` which is just a wrapper for `itnumpar.sty`.

**Comment by simonkramer** [comment]
Then (to summarise):
1. the latest delivery on CTAN (dated 2014-07-18)
2. the latest MacTeX-2014 distribution (dated 2014-05-25) 
must be updated.

**Comment by nlct** [comment]
@vincentb1 Do you want to upload the latest version to CTAN or shall I?

**Comment by vincentb1** [comment]
@nlct  I just made the delivery of 3.01. Thank you for the reminder and sorry for not being so reactive, In am quite busy these times&hellip;
