### ISSUE TITLE
Wrong \ordinalnum{1} in French

### ISSUE THREAD

**Issue by dbitouze** [nlct/fmtcount#20]
Currently:

 Package         | Version    
-----------------|------------
 fmtcount.sty    | 2015/05/05 
 fcprefix.sty    | 2012/09/28 
 fcnumparser.sty | 2012/09/28 
 fc-french.def   | 2012/10/24 
the same example as in https://github.com/nlct/fmtcount/issues/16 shows `\ordinalnum{1}` is wrong in French (`1e` instead of `1er`):
```latex
\documentclass[french]{minimal}
\usepackage{babel}
\usepackage{fmtcount}
\usepackage{array}
\usepackage[active,tightpage]{preview}
\begin{document}
\begin{preview}
  \begin{tabular}{@{ }l@{ }l@{ }}
    babel&fmtcount\\\hline
    1\ier&\ordinalnum{1}\\
    2\ieme&\ordinalnum{2}\\
  \end{tabular}
\end{preview}
\end{document}
```
![test](https://cloud.githubusercontent.com/assets/1032633/11898818/1018d124-a59b-11e5-8902-aea8c7a79d53.png)

**Comment by vincentb1** [comment]
Hello @dbitouze,
I have the same dates as you for the packages &mdash; OK, it seems that you are using the latest version on repo &mdash; however I get a different result:


![essai1](https://cloud.githubusercontent.com/assets/5001763/11928096/571f45fc-a7d1-11e5-99b2-972207f19b04.png)

**Comment by dbitouze** [comment]
Hello @vincentb1

Indeed, it works properly this morning :$ Really sorry for the noise.

**Comment by vincentb1** [comment]
Ok, good to know that there aren't any ghost in the machine :relieved: !
