### ISSUE TITLE
Problems with file: fc-spanish.def

### ISSUE THREAD

**Issue by ZElvis** [nlct/fmtcount#5]
The current version of the file fc-spanish.def  has errors that the previous one does not. You can't use \FCloadlang{spanish} or \numberstringnum{1} (with any number). 

The problems disappear if I put an old version of  fc-spanish.def (this one: http://texdoc.net/texmf-dist/tex/latex/fmtcount/fc-spanish.def)

Errors:
"C:\Program Files (x86)\MiKTeX 2.9\tex\latex\fmtcount\fc-spanish.def"
File: fc-spanish.def 2013/08/17

! Illegal parameter number in definition of \@ordinalMspanish.
<to be read again> 
                   2
l.53   \edef#2
              {\number#1\relax\noexpand\fmtord{o}}%
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.
! Missing { inserted.
l.55 \gdef\@ordinalFspanish}
                            [2]{%
Where was the left brace? You said something like `\def\a}',
which I'm going to interpret as`\def\a{}'.

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.55 \gdef\@ordinalFspanish}[
                             2]{%
You're in trouble here.  Try typing  <return>  to proceed.
If that doesn't work, type  X <return>  to quit.

! Missing control sequence inserted.
<inserted text> 
                \inaccessible 
l.56   \edef#
             2{\number#1\relax\noexpand\fmtord{a}}%
Please don't say `\def cs{...}', say`\def\cs{...}'.
I've inserted an inaccessible control sequence so that your
definition will be completed without mixing me up too badly.
You can recover graciously from this error, if you're
careful; see exercise 27.2 in The TeXbook.

! Parameters must be numbered consecutively.
<to be read again> 
                   2
l.56   \edef#2
              {\number#1\relax\noexpand\fmtord{a}}%
I've inserted the digit you should have used after the #.
Type `1' to delete what you did use.

! Missing number, treated as zero.
<to be read again> 
                   ##
l.56   \edef#2{\number#
                       1\relax\noexpand\fmtord{a}}%
A number should have been here; I inserted `0'.
(If you can't figure out why I needed to see a number,
look up`weird error' in the index to The TeXbook.)

**Comment by simonkramer** [comment]
I get the same error message with /usr/local/texlive/2014/texmf-dist/tex/latex/fmtcount/fc-spanish.def

**Comment by simonkramer** [comment]
I get the same error message with /usr/local/texlive/2014/texmf-dist/tex/latex/fmtcount/fc-spanish.def
